### ISSUE TITLE
Cursor over highlight off in Vimr

### ISSUE THREAD

**Issue by bronzehedwick** [gruvbox-community/gruvbox#121]
_NOTE: Maybe this should go in the Vimr issue queue? But see below._

When your cursor is over highlighted text in Vimr, only a slight outline of the letter below is visible.
![gruvbox-highlight-1](https://user-images.githubusercontent.com/637174/64883502-884b0100-d62d-11e9-928d-4a2291fdd5fb.png)

This does not happen in the terminal, or in the other GUI I tested, neovim-qt. 

However, it does _not_ happen in Vimr in other themes. Example below of Oceanic Next and the default theme.
![oceanic-next-highlight](https://user-images.githubusercontent.com/637174/64883622-ce07c980-d62d-11e9-8483-844e549ebd0e.png)
![Screen Shot 2019-09-13 at 1 53 44 PM](https://user-images.githubusercontent.com/637174/64883684-f2fc3c80-d62d-11e9-99d6-c12425871ba0.png)

**Comment by rbong** [comment]
If this happens in Vimr and not other environments then it's a Vimr issue. Gruvbox might have certain highlight groups that cause this but Vimr should handle it like other environments. Since Vimr is a custom GUI and other environments aren't mentioned in this issue, I'm heavily inclined to believe that this is a problem with Vimr's highlight rendering and has little to do with Gruvbox.

Vimr will probably need you to describe what highlight group rules are causing the issue. You should check the following highlight groups:

```
:hi Search
:hi Cursor
```

You can also use [this command](https://vim.fandom.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor) to check any other highlight groups under the cursor.

Please feel free to reopen if I'm wrong and the problem is with Gruvbox.

**Comment by bronzehedwick** [comment]
Thanks! I'll open an issue in the Vimr project.
