### ISSUE TITLE
Markdown heading colors changed in 

### ISSUE THREAD

**Issue by josephmidura** [gruvbox-community/gruvbox#194]
The update from September caused heading colors in markdown files (.md) to change. Was this intentional? The orange color in the pre September version provided some welcome contrast compared to the color of the non-heading text.

Pre September 2023 colors:
![Screen Shot 2023-11-15 at 12 31 05 PM](https://github.com/gruvbox-community/gruvbox/assets/11523557/e6a4a592-72ff-4a44-8038-fa4642361284)
Post September 2023 colors:
<img width="798" alt="Screenshot 2023-11-15 at 12 42 08 PM" src="https://github.com/gruvbox-community/gruvbox/assets/11523557/b0065cf0-6841-4747-9b17-e23449e25d8c">

**Comment by cassanof** [comment]
yeah not sure what happened in september... i will fork the old one; all my colorschemes are messed up

**Comment by cassanof** [comment]
https://github.com/cassanof/gruvbox

**Comment by rbong** [comment]
>The update from September caused heading colors in markdown files (.md) to change. Was this intentional?

This appears to be because we now define new Neovim highlight groups - see #188 . This should now be fixed.

>all my colorschemes are messed up

This is related to a degree, but has other factors as well.

In September, an effort was made to make language syntax colors much more consistent and customizable than they were before.

Languages that are part of Gruvbox are, for the most part, user submitted, and this means that basically all of them use different colors for what is essentially the same syntax. The definition of new Neovim highlight groups, particularly LSP highlight groups, means that consistency is a bigger problem than it ever was before.

That's why, with the new new highlight groups, I also changed all existing highlight groups to use colors more consistently since this is a breaking change anyways and comes with a new major version.

I realize that if you have a ton of custom colorschemes, this will break those, and I apologize. Please realize that better consistency comes with advantages - for example HTML, XHTML, and JSX will all look the same - TOML and YAML will look the same - JS and JSON will look similar - C like languages will all look similar - etc.

I'd argue that it's much better to stick around and help us improve these new highlight groups - I'm also looking to implement a few options that would make things act the exact same as they were before, namely:

* `g:gruvbox_legacy_syntax`: Use the old syntax colors when this is `1`.
* `g:gruvbox_tree_sitter`: Disable new Neovim 8 highlight groups when this is `0`.

**Comment by rbong** [comment]
You can now use these settings if you want to change syntax groups to what they were before:

```vim
let g:gruvbox_legacy_language_groups = 1
let g:gruvbox_treesitter = 0
```

Please note that if you do use Treesitter for highlighting it still won't look right.

**Comment by rbong** [comment]
>Please note that if you do use Treesitter for highlighting it still won't look right.

And it looks like from the screenshot in the OP that you do use Treesitter, which is what causes this issue.

**Comment by josephmidura** [comment]
> > Please note that if you do use Treesitter for highlighting it still won't look right.
> 
> And it looks like from the screenshot in the OP that you do use Treesitter, which is what causes this issue.

The screenshots in the OP were made in Terminal.app in MacOS 13.6.1 (Ventura). I don't user Treesitter. I can verify though, that setting this option sets the markdown syntax highlighting as it used to be pre-Sept. 2023:

```viml
let g:gruvbox_legacy_language_groups = 1
```

Thanks for the solution. I agree that increased standardization will be beneficial.

**Comment by rbong** [comment]
>I don't user Treesitter

Interesting, I can't recreate it without Treesitter. I'm glad the solution works for you.
